apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k2bridge.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k2bridge.name" . }}
    helm.sh/chart: {{ include "k2bridge.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  bridgeListenerAddress: "{{ .Values.settings.bridgeListenerAddress }}"
  metadataElasticAddress: "{{ .Values.settings.metadataElasticAddress }}"
  isHandleMetadata: "{{ .Values.settings.isHandleMetadata }}"
  kustoClusterUrl: "{{ .Values.settings.kustoClusterUrl }}"
  kustoDatabase: "{{ .Values.settings.kustoDatabase }}"
  kustoAadClientId: "{{ .Values.settings.kustoAadClientId }}"
  kustoAadTenantId: "{{ .Values.settings.kustoAadTenantId }}"
  useAspNetCore: "false"
